package groowt.intellij.wvc.psi

object WvcElementTypes {
    val compilationUnit = WvcElementType("compilationUnit")
    val preamble = WvcElementType("preamble")
    val body = WvcElementType("body")
    val bodyText = WvcElementType("bodyText")
    val gStringBodyText = WvcElementType("gStringBodyText")
    val jStringBodyText = WvcElementType("jStringBodyText")
    val gStringBodyTextGroovyElement = WvcElementType("gStringBodyTextGroovyElement")
    val component = WvcElementType("component")
    val selfClosingComponent = WvcElementType("selfClosingComponent")
    val componentWithChildren = WvcElementType("componentWithChildren")
    val openComponent = WvcElementType("openComponent")
    val closingComponent = WvcElementType("closingComponent")
    val fragmentComponent = WvcElementType("fragmentComponent")
    val componentArgs = WvcElementType("componentArgs")
    val componentType = WvcElementType("componentType")
    val componentConstructor = WvcElementType("componentConstructor")
    val attr = WvcElementType("attr")
    val keyValueAttr = WvcElementType("keyValueAttr")
    val booleanAttr = WvcElementType("booleanAttr")
    val value = WvcElementType("value")
    val gStringAttrValue = WvcElementType("gStringAttrValue")
    val jStringAttrValue = WvcElementType("jStringAttrValue")
    val closureAttrValue = WvcElementType("closureAttrValue")
    val componentAttrValue = WvcElementType("componentAttrValue")
    val equalsScriptlet = WvcElementType("equalsScriptlet")
    val plainScriptlet = WvcElementType("plainScriptlet")
    val dollarScriptlet = WvcElementType("dollarScriptlet")
    val dollarReference = WvcElementType("dollarReference")
}
